version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    labels:
      - "dependabot"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "System.Text.Json"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "Microsoft.Extensions.Hosting"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "Microsoft.Extensions.Hosting.Abstractions"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "Microsoft.CodeAnalysis"
        versions:
          - "5.3.0"
      - dependency-name: "Microsoft.CodeAnalysis.CSharp"
        versions:
          - "5.3.0"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependabot"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "release-drafter/release-drafter"

  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependabot"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    labels:
      - "dependabot"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - "dependabot"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
