//HintName: MinimalLambda.DurableHandlers.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}

namespace MinimalLambda.Generated
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.DurableExecution;
    using Microsoft.Extensions.DependencyInjection;
    using MinimalLambda;
    using MinimalLambda.Builder;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    file static class GeneratedDurableLambdaInvocationBuilderExtensions
    {
        [InterceptsLocation(1, "REPLACED")]
        internal static ILambdaInvocationBuilder MapDurableHandlerInterceptor0(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, global::System.Threading.Tasks.Task (string arg0, global::Amazon.Lambda.DurableExecution.IDurableContext arg1) => throw null!);

            application.Handle(InvocationDelegate);

            return application;

            async Task InvocationDelegate(ILambdaInvocationContext context)
            {
                var invocationData = context.Features.GetRequired<IInvocationDataFeature>();
                var envelope = context.Serializer.Deserialize<DurableExecutionInvocationInput>(
                    invocationData.EventStream);
                var output = await DurableFunction.WrapAsync<string>(
                    (input, durableContext) =>
                    {
                        var arg0 = input;
                        var arg1 = durableContext;
                        return castHandler.Invoke(arg0, arg1);
                    },
                    envelope,
                    context).ConfigureAwait(false);

                invocationData.ResponseStream.SetLength(0L);
                context.Serializer.Serialize(output, invocationData.ResponseStream);
                invocationData.ResponseStream.Position = 0L;
            }
        }
        [InterceptsLocation(1, "REPLACED")]
        internal static ILambdaInvocationBuilder MapDurableHandlerInterceptor1(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, global::System.Threading.Tasks.Task (int arg0, global::Amazon.Lambda.DurableExecution.IDurableContext arg1) => throw null!);

            application.Handle(InvocationDelegate);

            return application;

            async Task InvocationDelegate(ILambdaInvocationContext context)
            {
                var invocationData = context.Features.GetRequired<IInvocationDataFeature>();
                var envelope = context.Serializer.Deserialize<DurableExecutionInvocationInput>(
                    invocationData.EventStream);
                var output = await DurableFunction.WrapAsync<int>(
                    (input, durableContext) =>
                    {
                        var arg0 = input;
                        var arg1 = durableContext;
                        return castHandler.Invoke(arg0, arg1);
                    },
                    envelope,
                    context).ConfigureAwait(false);

                invocationData.ResponseStream.SetLength(0L);
                context.Serializer.Serialize(output, invocationData.ResponseStream);
                invocationData.ResponseStream.Position = 0L;
            }
        }
        [InterceptsLocation(1, "REPLACED")]
        internal static ILambdaInvocationBuilder MapDurableHandlerInterceptor2(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, global::System.Threading.Tasks.Task (long arg0, global::Amazon.Lambda.DurableExecution.IDurableContext arg1) => throw null!);

            application.Handle(InvocationDelegate);

            return application;

            async Task InvocationDelegate(ILambdaInvocationContext context)
            {
                var invocationData = context.Features.GetRequired<IInvocationDataFeature>();
                var envelope = context.Serializer.Deserialize<DurableExecutionInvocationInput>(
                    invocationData.EventStream);
                var output = await DurableFunction.WrapAsync<long>(
                    (input, durableContext) =>
                    {
                        var arg0 = input;
                        var arg1 = durableContext;
                        return castHandler.Invoke(arg0, arg1);
                    },
                    envelope,
                    context).ConfigureAwait(false);

                invocationData.ResponseStream.SetLength(0L);
                context.Serializer.Serialize(output, invocationData.ResponseStream);
                invocationData.ResponseStream.Position = 0L;
            }
        }
        [InterceptsLocation(1, "REPLACED")]
        internal static ILambdaInvocationBuilder MapDurableHandlerInterceptor3(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, global::System.Threading.Tasks.Task (decimal arg0, global::Amazon.Lambda.Core.ILambdaContext arg1, global::Amazon.Lambda.DurableExecution.IDurableContext arg2, global::MinimalLambda.ILambdaInvocationContext arg3, global::Amazon.Lambda.Core.ILambdaContext arg4) => throw null!);

            application.Handle(InvocationDelegate);

            return application;

            async Task InvocationDelegate(ILambdaInvocationContext context)
            {
                var invocationData = context.Features.GetRequired<IInvocationDataFeature>();
                var envelope = context.Serializer.Deserialize<DurableExecutionInvocationInput>(
                    invocationData.EventStream);
                var output = await DurableFunction.WrapAsync<decimal>(
                    (input, durableContext) =>
                    {
                        var arg0 = input;
                        var arg1 = context;
                        var arg2 = durableContext;
                        var arg3 = context;
                        var arg4 = context;
                        return castHandler.Invoke(arg0, arg1, arg2, arg3, arg4);
                    },
                    envelope,
                    context).ConfigureAwait(false);

                invocationData.ResponseStream.SetLength(0L);
                context.Serializer.Serialize(output, invocationData.ResponseStream);
                invocationData.ResponseStream.Position = 0L;
            }
        }
    }

    file static class Utilities
    {
        internal static T Cast<T>(Delegate d, T _) where T : Delegate => (T)d;
    }
}
