//HintName: MinimalLambda.DurableHandlers.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}

namespace MinimalLambda.Generated
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.DurableExecution;
    using Microsoft.Extensions.DependencyInjection;
    using MinimalLambda;
    using MinimalLambda.Builder;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    file static class GeneratedDurableLambdaInvocationBuilderExtensions
    {
        [InterceptsLocation(1, "REPLACED")]
        internal static ILambdaInvocationBuilder MapDurableHandlerInterceptor0(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, (global::DurableHandler)null!);

            application.Handle(InvocationDelegate);

            return application;

            async Task InvocationDelegate(ILambdaInvocationContext context)
            {
                var invocationData = context.Features.GetRequired<IInvocationDataFeature>();
                var serializer = context.ServiceProvider.GetRequiredService<Amazon.Lambda.Core.ILambdaSerializer>();
                var envelope = serializer.Deserialize<DurableExecutionInvocationInput>(
                    invocationData.EventStream);
                var output = await DurableFunction.WrapAsync<string>(
                    (input, durableContext) =>
                    {
                        var arg0 = input;
                        var arg1 = durableContext;
                        return castHandler.Invoke(arg0, arg1);
                    },
                    envelope,
                    context).ConfigureAwait(false);

                invocationData.ResponseStream.SetLength(0L);
                serializer.Serialize(output, invocationData.ResponseStream);
                invocationData.ResponseStream.Position = 0L;
            }
        }
    }

    file static class Utilities
    {
        internal static T Cast<T>(Delegate d, T _) where T : Delegate => (T)d;
    }
}
