//HintName: MinimalLambda.DurableHandlers.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System.CodeDom.Compiler;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}

namespace MinimalLambda.Generated
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;
    using Amazon.Lambda.DurableExecution;
    using Microsoft.Extensions.DependencyInjection;
    using MinimalLambda;
    using MinimalLambda.Builder;

    [global::System.CodeDom.Compiler.GeneratedCode("MinimalLambda.SourceGenerators", "REPLACED")]
    file static class GeneratedDurableLambdaInvocationBuilderExtensions
    {
        private const string EventFeatureProviderKey = "__EventFeatureProvider";
        private const string ResponseFeatureProviderKey = "__ResponseFeatureProvider";

        [InterceptsLocation(1, "REPLACED")]
        internal static ILambdaInvocationBuilder MapDurableHandlerInterceptor0(
            this ILambdaInvocationBuilder application,
            Delegate handler
        )
        {
            var castHandler = Utilities.Cast(handler, global::System.Threading.Tasks.Task<string> (global::IService arg0, global::MinimalLambda.ILambdaInvocationContext arg1, string arg2, global::Amazon.Lambda.Core.ILambdaContext arg3, global::IService? arg4 = default, global::Amazon.Lambda.DurableExecution.IDurableContext arg5 = default, global::IService arg6 = default) => throw null!);

            application.Handle(InvocationDelegate);
            DurableTerminalInfrastructure.Register(application);

            if (!application.Properties.ContainsKey(EventFeatureProviderKey))
                application.Properties[EventFeatureProviderKey] = application
                    .Services.GetRequiredService<IEventFeatureProviderFactory>()
                    .Create<DurableExecutionInvocationInput>();

            if (!application.Properties.ContainsKey(ResponseFeatureProviderKey))
                application.Properties[ResponseFeatureProviderKey] = application
                    .Services.GetRequiredService<IResponseFeatureProviderFactory>()
                    .Create<DurableExecutionInvocationOutput>();

            return application;

            async Task InvocationDelegate(ILambdaInvocationContext context)
            {
                DurableTerminalInfrastructure.Enter(context);

                var envelope = context.GetRequiredEvent<DurableExecutionInvocationInput>();
                var output = await DurableFunction.WrapAsync<string, string>(
                    (input, durableContext) =>
                    {
                        if (context.ServiceProvider.GetService<IServiceProviderIsService>() is not IServiceProviderIsKeyedService)
                        {
                            throw new InvalidOperationException($"Unable to resolve service referenced by {nameof(FromKeyedServicesAttribute)}. The service provider doesn't support keyed services.");
                        }
                        var arg0 = context.ServiceProvider.GetRequiredService<global::IService>();
                        var arg1 = context;
                        var arg2 = input;
                        var arg3 = context;
                        var arg4 = context.ServiceProvider.GetService<global::IService?>();
                        var arg5 = durableContext;
                        var arg6 = context.ServiceProvider.GetKeyedService<global::IService>("key");
                        return castHandler.Invoke(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                    },
                    envelope,
                    context).ConfigureAwait(false);

                if (context.Features.Get<IResponseFeature>() is not IResponseFeature<DurableExecutionInvocationOutput> responseFeature)
                {
                    throw new InvalidOperationException($"Response feature for type '{typeof(DurableExecutionInvocationOutput).FullName}' is not available in the collection.");
                }

                responseFeature.SetResponse(output);
                DurableTerminalInfrastructure.Complete(context);
            }
        }
    }

    file static class Utilities
    {
        internal static T Cast<T>(Delegate d, T _) where T : Delegate => (T)d;
    }
}
