<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MinimalLambda" Version="$(CorePackageVersion)" />
    <PackageReference Include="MinimalLambda.DurableExecution" Version="$(DurablePackageVersion)" />
    <PackageReference Include="Amazon.Lambda.DurableExecution" Version="1.0.0" />
  </ItemGroup>
</Project>
