name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    branches: [main]

permissions:
  pull-requests: read
  statuses: write

concurrency:
  group: pr-title-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pr-title-check:
    uses: LayeredCraft/devops-templates/.github/workflows/pr-title-check.yml@fa7aa89e829a2b7bb947f5c38ba456189831534a # v10.3
